name=Time_Manager
version=1.1.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Manajemen waktu offline ringan untuk ESP32 dengan pyserial, NVS dan RTC RAM fallback.
paragraph=Pustaka ini memungkinkan sinkronisasi waktu satu kali via serial (Python) dan menjaganya tetap hidup saat soft-restart menggunakan RTC RAM.
category=Timing
url=https://github.com/0ADILL3/Time_Manager
architectures=esp32
includes=Time_Manager.h